# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: E1sewhere
subtitle:
description: none
author: E1se
language: zh-Hans
timezone:
avatar: /images/eva1.ico

#live2d
live2d:
  enable: false
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-shizuku #模板目录，在node_modules里
  display:
    position: left
    width: 100 
    height: 250
  mobile:
    show: false  #是否在手机进行显示


#search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://e1sewhere.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - CNAME
  - baidu_verify_14JSy8Fa9y.html #下载的文件名

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false #true
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: mnext

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repository: git@github.com:E1sewhere/E1sewhere.github.io.git
  branch: master
- type: baidu_url_submitter ## 这是新加的
  
  
  # 自动生成sitemap
sitemap: 
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
  
  # 百度提交
baidu_url_submit:
  count: 10 ## 提交最新的一个链接
  host: e1sewhere.github.io ## 在百度站长平台中注册的域名
  token: Dvtbr1m0iQISGOR4 ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

# Hexo跨博客文章推荐插件
recommended_posts:
  server: https://api.truelaurel.com #后端推荐服务器地址
  timeoutInMillis: 10000 #服务时长，超过此时长，则使用离线推荐模式
  internalLinks: 3 #内部文章数量
  externalLinks: 1 #外部文章数量
  fixedNumber: false
  autoDisplay: true #自动在文章底部显示推荐文章
  excludePattern: []
  titleHtml: <h1>RECOMMEND<span style="font-size:0.45em; color:gray">（power by <a href="https://github.com/huiwang/hexo-recommended-posts">hexo recommended</a>）</span></h1> #自定义标题